### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by MouseWithBeer** [insideone/pagywosg#13]
It would be nice to have some kind of FAQ/Q&A page that explains the basics of the site/event.

@Ardiffaz I would appreciate if you would just quickly go over it once I am done with it just to make sure it doesn't have any obvious flaws or look too ugly :)

**Comment by Ardiffaz** [comment]
I've added the template for FAQ page, so you just need to add texts into array ( src/Frontend/pages/FaqPage.vue, line 42 and further). 
IDs are needed to be able to give a direct link to one particular question (then the page will be scrolled to it, and also it will be highlighted).

**Comment by MouseWithBeer** [comment]
Oh, that is even more than what I wanted to do, thank you! Pulling to local so I can add the text in.
