### ISSUE TITLE
Mobile experience

### ISSUE THREAD

**Issue by Ardiffaz** [insideone/pagywosg#17]
Needs checking if it works on mobile, and fixing if not.

**Comment by MouseWithBeer** [comment]
The background cuts out if you scroll sideways (same on every page, see screenshot) 
but other than that seems to be working fine to me.

Tested on Mobile Firefox 64.0.1 on Android 7.1.2 (Lineage OS 14.1 for Samsung Note 3)

![Screenshot_20190614-220229](https://user-images.githubusercontent.com/12525757/59535131-69cf4f80-8ef0-11e9-974e-47d32b181f7d.png)

**Comment by MouseWithBeer** [comment]
Updated on server and tested on both an Iphone and my own. Works fine now.
