### ISSUE TITLE
Adding SteamGifts User Name Broke Registration

### ISSUE THREAD

**Issue by raymondlaw** [insideone/pagywosg#21]
When registering for the first time, Steam login only gives Steam information and not SteamGifts information.  SteamGifts information cannot be null which causes a data integrity error.  Suggested fix: change database type for SteamGifts information to allow nulls and have an update option to append that information on afterwards.

`
{"errors":[{"type":"exception","message":"An exception occurred while executing \u0027INSERT INTO users (enabled, steam_id, community_visibility_state, profile_state, profile_name, sg_profile_name, last_log_off, comment_permission, profile_url, avatar, persona_state, primary_clan_id, join_date, country_code, roles) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\u0027 with params [1, \u002276561198012679672\u0022, 3, 1, \u0022rlaw100\u0022, null, \u00222019-06-23 04:32:27\u0022, null, \u0022https:\\\/\\\/steamcommunity.com\\\/id\\\/rlaw100\\\/\u0022, \u0022https:\\\/\\\/steamcdn-a.akamaihd.net\\\/steamcommunity\\\/public\\\/images\\\/avatars\\\/81\\\/81f96a917355381f7352d83b197284136b5a2e0a_full.jpg\u0022, 1, 103582791456950284, \u00222009-08-09 19:56:18\u0022, null, \u0022[]\u0022]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column \u0027sg_profile_name\u0027 cannot be null"}]}
`

**Comment by insideone** [comment]
Thanks for noticing. Fix is served and should be deployed (@MouseWithBeer) to the server soon.

**Comment by MouseWithBeer** [comment]
Sorry for the late response, I wasn't home. It is now deployed on the server. @raymondlaw please try if it works now :)
