### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by insideone** [insideone/pagywosg#4]

**Comment by insideone** [comment]
@MouseWithBeer at least it works :-)
![image](https://user-images.githubusercontent.com/16841572/58828869-15ee7c00-864f-11e9-8192-49a329c970e7.png)

**Comment by MouseWithBeer** [comment]
It doesn't indeed. Have you by any chance also changed anything so it wont constantly sign you out by itself like it did till now?

**Comment by insideone** [comment]
session time has been prolonged in 490466d5
I hope it helped. If not, we will just need a new issue :-)
