### ISSUE TITLE
Playtime tracking for "Steam is learning" games

### ISSUE THREAD

**Issue by insideone** [insideone/pagywosg#5]
Playtime doesn't track "Steam is learning" games through Steam API. So we have to find and implement a workaround

**Comment by insideone** [comment]
GET https://steamcommunity.com/profiles/76561198106641748/games/?tab=all&l=english
/rgGames/

**Comment by Ardiffaz** [comment]
`https://api.steampowered.com/IPlayerService/GetRecentlyPlayedGames/v1/?key=XXXXXX&steamid=76561198071848932`
It has playtime for _Profile Limited_ game (appID 862250, "Danger!Energy")

**Comment by insideone** [comment]
@MouseWithBeer it's just been fixed through GetRecentlyPlayedGames. I think it should work in most cases

**Comment by MouseWithBeer** [comment]
Tested with one of my "Steam is still learning about" games and it seems to work: https://i.imgur.com/nUFHGnV.png will keep an eye on it in the future to see if any issues pop up.

@Ardiffaz nice find!
